analyzers:
  speaker:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: speaker
    contains: ": speaker"

  joystick:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: joystick
    contains: ": Joystick"

  # Discard all other diagnostics
  other:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: other
    contains: "/"
