analyzers:
  emergency_system:
    type: diagnostic_aggregator/AnalyzerGroup
    path: emergency_system
    analyzers:
      topic_status:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_status
        contains: ": emergency_system_topic_status"
        timeout: 1.0
        num_items: 0
