analyzers:
  localization:
    type: diagnostic_aggregator/AnalyzerGroup
    path: localization
    analyzers:
      topic_status:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_status
        contains: ": localization_topic_status"
        timeout: 1.0
        num_items: 0

      tf_status:
        type: diagnostic_aggregator/GenericAnalyzer
        path: tf_status
        contains: ": localization_tf_status"
        timeout: 1.0
        num_items: 0

      ndt_scan_matcher:
        type: diagnostic_aggregator/GenericAnalyzer
        path: ndt_scan_matcher
        contains: "ndt_scan_matcher"
        timeout: 1.0
        num_items: 0
