type: diagnostic_aggregator/AnalyzerGroup
path: map
analyzers:
  topic_status:
    type: diagnostic_aggregator/GenericAnalyzer
    path: topic_status
    contains: ": map_topic_status"
    timeout: 1.0
    num_items: 0

  map_version:
    type: diagnostic_aggregator/GenericAnalyzer
    path: map_version
    contains: ": map_version"
    timeout: 0.0
    num_items: 0
