analyzers:
  vehicle:
    type: diagnostic_aggregator/AnalyzerGroup
    path: vehicle
    analyzers:
      topic_status:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_status
        contains: ": vehicle_topic_status"
        timeout: 1.0
        num_items: 0

      vehicle_mcu_connection:
        type: diagnostic_aggregator/GenericAnalyzer
        path: vehicle_mcu_connection
        contains: ": vehicle_mcu_connection"
        timeout: 1.0
        num_items: 0
